{"variants":[{"paths":["\/documentation\/trustlesssdk\/kycbasefieldprotocol\/puterror(error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Records an error encountered during field validation."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"putError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"KYCFieldValidationError","preciseIdentifier":"s:12TrustlessSDK23KYCFieldValidationErrorV","kind":"typeIdentifier","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/KYCFieldValidationError"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The validation error to record."}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/KYCBaseFieldProtocol"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/KYCBaseFieldProtocol\/putError(error:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"putError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12TrustlessSDK23KYCFieldValidationErrorV","text":"KYCFieldValidationError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:12TrustlessSDK20KYCBaseFieldProtocolP8putError5erroryAA018KYCFieldValidationG0V_tF","modules":[{"name":"TrustlessSDK"}],"roleHeading":"Instance Method","required":true,"role":"symbol","title":"putError(error:)","symbolKind":"method"},"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/KYCBaseFieldProtocol":{"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/KYCBaseFieldProtocol","role":"symbol","type":"topic","title":"KYCBaseFieldProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"KYCBaseFieldProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"KYCBaseFieldProtocol","kind":"identifier"}],"url":"\/documentation\/trustlesssdk\/kycbasefieldprotocol","abstract":[{"type":"text","text":"Defines the protocol for a base KYC field, including validation and error handling."}],"kind":"symbol"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/KYCFieldValidationError":{"abstract":[{"type":"text","text":"Encapsulates validation error messages for KYC fields in both English and Arabic."}],"url":"\/documentation\/trustlesssdk\/kycfieldvalidationerror","navigatorTitle":[{"text":"KYCFieldValidationError","kind":"identifier"}],"title":"KYCFieldValidationError","type":"topic","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/KYCFieldValidationError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"KYCFieldValidationError"}],"kind":"symbol","role":"symbol"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"title":"TrustlessSDK","url":"\/documentation\/trustlesssdk","role":"collection","type":"topic","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","abstract":[],"kind":"symbol"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/KYCBaseFieldProtocol/putError(error:)":{"role":"symbol","title":"putError(error:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"putError","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"KYCFieldValidationError","kind":"typeIdentifier","preciseIdentifier":"s:12TrustlessSDK23KYCFieldValidationErrorV"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/KYCBaseFieldProtocol\/putError(error:)","abstract":[{"text":"Records an error encountered during field validation.","type":"text"}],"required":true,"kind":"symbol","url":"\/documentation\/trustlesssdk\/kycbasefieldprotocol\/puterror(error:)"}}}