{"seeAlsoSections":[{"identifiers":["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"],"generated":true,"title":"Request and Response"}],"sections":[],"variants":[{"paths":["\/documentation\/trustlesssdk\/resultvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"typealias","roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResultValue"}],"title":"ResultValue","modules":[{"name":"TrustlessSDK"}],"externalID":"s:12TrustlessSDK11ResultValuea"},"abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"type":"codeVoice","code":"TrustlessError"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"},{"kind":"text","text":"<"},{"text":"Value","kind":"genericParameter"},{"kind":"text","text":"> = "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:12TrustlessSDK11ResultValuea0D0xmfp"},{"kind":"text","text":", "},{"text":"TrustlessError","preciseIdentifier":"s:12TrustlessSDK0A5ErrorO","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"Value","content":[{"inlineContent":[{"text":"The type of the value in the success case.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This type simplifies the handling of operations that can either succeed with a value of type ","type":"text"},{"code":"Value","type":"codeVoice"},{"type":"text","text":" or fail with a "},{"type":"codeVoice","code":"TrustlessError"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It is used extensively across the SDK in functions that perform asynchronous tasks, such as network requests, which can either produce a result or an error."}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"]]},"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/TrustlessError":{"title":"TrustlessError","url":"\/documentation\/trustlesssdk\/trustlesserror","abstract":[{"type":"text","text":"Describes errors that can occur within the TrustlessSDK."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrustlessError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TrustlessError"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","role":"symbol","type":"topic"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/CancelCallback":{"navigatorTitle":[{"text":"CancelCallback","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"A typealias for a closure used to cancel an ongoing operation."}],"type":"topic","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback","url":"\/documentation\/trustlesssdk\/cancelcallback","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CancelCallback"}],"kind":"symbol","title":"CancelCallback"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"title":"TrustlessSDK","url":"\/documentation\/trustlesssdk","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","role":"collection","type":"topic"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultValue":{"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultValue"}],"role":"symbol","type":"topic","kind":"symbol","title":"ResultValue","url":"\/documentation\/trustlesssdk\/resultvalue","navigatorTitle":[{"kind":"identifier","text":"ResultValue"}],"abstract":[{"text":"A typealias for the ","type":"text"},{"code":"Result","type":"codeVoice"},{"text":" type specialized for the TrustlessSDK, where failures are represented by ","type":"text"},{"type":"codeVoice","code":"TrustlessError"},{"type":"text","text":"."}]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultCallback":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultCallback","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","abstract":[{"type":"text","text":"A typealias for a callback function that is invoked with a "},{"type":"codeVoice","code":"ResultValue"},{"text":".","type":"text"}],"title":"ResultCallback","type":"topic","url":"\/documentation\/trustlesssdk\/resultcallback","navigatorTitle":[{"text":"ResultCallback","kind":"identifier"}],"kind":"symbol"}}}