{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/trustlesssdk\/resultvalue"]}],"metadata":{"role":"symbol","title":"ResultValue","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}],"modules":[{"name":"TrustlessSDK"}],"externalID":"s:12TrustlessSDK11ResultValuea","roleHeading":"Type Alias","symbolKind":"typealias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResultValue"}]},"seeAlsoSections":[{"title":"Request and Response","generated":true,"identifiers":["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"code":"TrustlessError","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ResultValue","kind":"identifier"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"Value"},{"text":"> = ","kind":"text"},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:s6ResultO"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:12TrustlessSDK11ResultValuea0D0xmfp","kind":"typeIdentifier","text":"Value"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"TrustlessError","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","preciseIdentifier":"s:12TrustlessSDK0A5ErrorO"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of the value in the success case."}]}],"name":"Value"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This type simplifies the handling of operations that can either succeed with a value of type ","type":"text"},{"type":"codeVoice","code":"Value"},{"type":"text","text":" or fail with a "},{"type":"codeVoice","code":"TrustlessError"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It is used extensively across the SDK in functions that perform asynchronous tasks, such as network requests, which can either produce a result or an error."}]}]}],"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/TrustlessError":{"role":"symbol","url":"\/documentation\/trustlesssdk\/trustlesserror","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TrustlessError","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Describes errors that can occur within the TrustlessSDK."}],"title":"TrustlessError","navigatorTitle":[{"kind":"identifier","text":"TrustlessError"}],"kind":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/CancelCallback":{"title":"CancelCallback","url":"\/documentation\/trustlesssdk\/cancelcallback","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CancelCallback","kind":"identifier"}],"navigatorTitle":[{"text":"CancelCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A typealias for a closure used to cancel an ongoing operation.","type":"text"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","url":"\/documentation\/trustlesssdk","title":"TrustlessSDK","role":"collection","abstract":[]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultCallback":{"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResultCallback"}],"title":"ResultCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"A typealias for a callback function that is invoked with a "},{"code":"ResultValue","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/trustlesssdk\/resultcallback","type":"topic"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultValue":{"url":"\/documentation\/trustlesssdk\/resultvalue","title":"ResultValue","role":"symbol","abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"code":"TrustlessError","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","type":"topic","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}]}}}