{"kind":"symbol","metadata":{"modules":[{"name":"TrustlessSDK"}],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResultValue"}],"roleHeading":"Type Alias","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}],"title":"ResultValue","externalID":"s:12TrustlessSDK11ResultValuea","symbolKind":"typealias"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue"},"seeAlsoSections":[{"title":"Request and Response","identifiers":["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"]]},"sections":[],"abstract":[{"text":"A typealias for the ","type":"text"},{"type":"codeVoice","code":"Result"},{"text":" type specialized for the TrustlessSDK, where failures are represented by ","type":"text"},{"type":"codeVoice","code":"TrustlessError"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Value","kind":"genericParameter"},{"text":"> = ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:s6ResultO"},{"text":"<","kind":"text"},{"text":"Value","kind":"typeIdentifier","preciseIdentifier":"s:12TrustlessSDK11ResultValuea0D0xmfp"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:12TrustlessSDK0A5ErrorO","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","text":"TrustlessError"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"Value","content":[{"type":"paragraph","inlineContent":[{"text":"The type of the value in the success case.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"This type simplifies the handling of operations that can either succeed with a value of type ","type":"text"},{"code":"Value","type":"codeVoice"},{"text":" or fail with a ","type":"text"},{"code":"TrustlessError","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It is used extensively across the SDK in functions that perform asynchronous tasks, such as network requests, which can either produce a result or an error."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/trustlesssdk\/resultvalue"]}],"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"role":"collection","kind":"symbol","title":"TrustlessSDK","type":"topic","url":"\/documentation\/trustlesssdk","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","abstract":[]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultValue":{"type":"topic","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ResultValue"}],"title":"ResultValue","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","role":"symbol","abstract":[{"type":"text","text":"A typealias for the "},{"code":"Result","type":"codeVoice"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"type":"codeVoice","code":"TrustlessError"},{"type":"text","text":"."}],"url":"\/documentation\/trustlesssdk\/resultvalue"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/TrustlessError":{"url":"\/documentation\/trustlesssdk\/trustlesserror","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Describes errors that can occur within the TrustlessSDK."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrustlessError","kind":"identifier"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/TrustlessError","navigatorTitle":[{"text":"TrustlessError","kind":"identifier"}],"title":"TrustlessError","kind":"symbol"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/CancelCallback":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback","url":"\/documentation\/trustlesssdk\/cancelcallback","abstract":[{"type":"text","text":"A typealias for a closure used to cancel an ongoing operation."}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CancelCallback","kind":"identifier"}],"title":"CancelCallback","navigatorTitle":[{"text":"CancelCallback","kind":"identifier"}],"role":"symbol"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultCallback":{"kind":"symbol","url":"\/documentation\/trustlesssdk\/resultcallback","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"A typealias for a callback function that is invoked with a "},{"code":"ResultValue","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"ResultCallback","kind":"identifier"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","title":"ResultCallback","role":"symbol"}}}