{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/trustlesssdk\/resultcallback"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK"]]},"abstract":[{"type":"text","text":"A typealias for a callback function that is invoked with a "},{"type":"codeVoice","code":"ResultValue"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResultCallback"},{"text":"<","kind":"text"},{"kind":"genericParameter","text":"Value"},{"text":"> = (","kind":"text"},{"text":"ResultValue","kind":"typeIdentifier","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","preciseIdentifier":"s:12TrustlessSDK11ResultValuea"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Value","preciseIdentifier":"s:12TrustlessSDK14ResultCallbacka5Valuexmfp"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The type of the value that is expected on success.","type":"text"}]}],"name":"Value"}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This callback is used to return the outcome of asynchronous operations throughout the SDK. It allows for elegant handling of both success and failure cases without the need for cumbersome error-checking code."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ResultCallback"},{"type":"text","text":" takes a single parameter of type "},{"type":"codeVoice","code":"ResultValue<Value>"},{"type":"text","text":", enabling the caller to handle success and failure through the "},{"code":"Result","type":"codeVoice"},{"type":"text","text":" typeâ€™s "},{"type":"codeVoice","code":".success"},{"text":" and ","type":"text"},{"type":"codeVoice","code":".failure"},{"text":" cases.","type":"text"}]}],"kind":"content"}],"metadata":{"roleHeading":"Type Alias","externalID":"s:12TrustlessSDK14ResultCallbacka","role":"symbol","modules":[{"name":"TrustlessSDK"}],"title":"ResultCallback","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ResultCallback","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ResultCallback"}]},"identifier":{"url":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","interfaceLanguage":"swift"},"seeAlsoSections":[{"title":"Request and Response","identifiers":["doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"],"generated":true}],"references":{"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/CancelCallback":{"title":"CancelCallback","url":"\/documentation\/trustlesssdk\/cancelcallback","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"CancelCallback","kind":"identifier"}],"navigatorTitle":[{"text":"CancelCallback","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A typealias for a closure used to cancel an ongoing operation.","type":"text"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/CancelCallback"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultCallback":{"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultCallback","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ResultCallback"}],"title":"ResultCallback","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ResultCallback","kind":"identifier"}],"abstract":[{"type":"text","text":"A typealias for a callback function that is invoked with a "},{"code":"ResultValue","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/trustlesssdk\/resultcallback","type":"topic"},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK/ResultValue":{"url":"\/documentation\/trustlesssdk\/resultvalue","title":"ResultValue","role":"symbol","abstract":[{"type":"text","text":"A typealias for the "},{"type":"codeVoice","code":"Result"},{"type":"text","text":" type specialized for the TrustlessSDK, where failures are represented by "},{"code":"TrustlessError","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultValue","kind":"identifier"}],"identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK\/ResultValue","type":"topic","navigatorTitle":[{"text":"ResultValue","kind":"identifier"}]},"doc://com.staq.TrustlessSDK/documentation/TrustlessSDK":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.staq.TrustlessSDK\/documentation\/TrustlessSDK","url":"\/documentation\/trustlesssdk","title":"TrustlessSDK","role":"collection","abstract":[]}}}